# Generated by Django 3.0.7 on 2021-06-12 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.CharField(max_length=30, verbose_name='単語')),
                ('ts', models.CharField(max_length=50, verbose_name='訳')),
                ('example', models.TextField(verbose_name='例文')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('browsed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終閲覧日')),
            ],
        ),
    ]
