# Generated by Django 3.0.7 on 2021-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(verbose_name='文')),
                ('ts', models.TextField(blank=True, verbose_name='訳')),
            ],
        ),
        migrations.AlterField(
            model_name='words',
            name='example',
            field=models.TextField(blank=True, verbose_name='例文'),
        ),
    ]
