# Generated by Django 3.0.7 on 2021-07-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ew', '0002_auto_20210705_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='pp',
            field=models.CharField(blank=True, max_length=30, verbose_name='過去分詞'),
        ),
        migrations.AddField(
            model_name='words',
            name='prp',
            field=models.CharField(blank=True, max_length=30, verbose_name='現在分詞'),
        ),
        migrations.AddField(
            model_name='words',
            name='pt',
            field=models.CharField(blank=True, max_length=30, verbose_name='過去形'),
        ),
    ]
