# Generated by Django 3.0.7 on 2021-08-28 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ew', '0003_auto_20210705_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='examples',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
