# Generated by Django 3.0.7 on 2021-10-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ew', '0005_words_wverb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='spell',
            field=models.CharField(max_length=30, unique=True, verbose_name='単語'),
        ),
    ]
