# Generated by Django 3.2.9 on 2022-03-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20201231_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='タイトルなし', max_length=50, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='tag',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='note.tags', verbose_name='付箋'),
        ),
    ]
